name: Update GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch SVGs from API
        run: |
          curl -s -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=Flukely&show_icons=true&theme=radical"
          curl -s -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=Flukely&layout=compact&theme=radical"

          if ! grep -q "<svg" github-stats.svg; then echo "Error fetching stats"; rm -f github-stats.svg; fi
          if ! grep -q "<svg" top-langs.svg; then echo "Error fetching langs"; rm -f top-langs.svg; fi

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          [ -f github-stats.svg ] && git add github-stats.svg
          [ -f top-langs.svg ] && git add top-langs.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: fix and update github stats svgs" && git push)
